---
title: "Initial cleaning of .csv files"
author: "Mackenzie Gray"
output:
  html_document:
    toc: yes
  pdf_document:
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 4
linkcolor: red
urlcolor: red
---


```{r eval=FALSE}
library(dplyr)
library(readr)
```

```{r eval=FALSE}

## This will load FY_02->FY_05 without errors.

## Doesn't output anything yet, need to decide what we are interested
## in/what columns we need, and be able to coerce the newer data into
## the same form.

dfl <- list(1:5)

for(i in 2:5){
    filename <- paste("../../data/raw/csv_copies/H1B_efile_FY0", as.character(i), ".txt", sep="")
    df <- read_csv(filename,
                   col_types=cols(MAX_RATE_2=col_double(),
                                  NBR_IMMIGRANTS=col_integer(),
                                  SUBMITTED_DATE=col_datetime(),
                                  BEGIN_DATE=col_date("%m/%d/%Y"),
                                  END_DATE=col_date("%m/%d/%Y"),
                                  JOB_CODE=col_character(),
                                  CERTIFIED_BEGIN_DATE=col_date("%m/%d/%Y"),
                                  CERTIFIED_END_DATE=col_date("%m/%d/%Y"),
                                  DOL_DECISION_DATE=col_date("%m/%d/%Y"),
                                  YR_SOURCE_PUB_1=col_date("%Y"),
                                  YR_SOURCE_PUB_2=col_date("%Y")
                                  ))

    ## Remove rows which are all NA
    df <- df %>% filter(rowSums(is.na(.)) != ncol(.))
    
    dfl[[i-1]] <- df

}
```

The data for FY2006 has a few wonky things, so we'll do it separately

```{r eval=FALSE}

i <- 6
filename <- paste("../../data/raw/csv_copies/H1B_efile_FY0", as.character(i), ".txt", sep="")
df <- read_csv(filename,
               col_types=cols(MAX_RATE_2=col_double(),
                              NBR_IMMIGRANTS=col_integer(),
                              SUBMITTED_DATE=col_datetime(),
                              BEGIN_DATE=col_date("%m/%d/%Y"),
                              END_DATE=col_date("%m/%d/%Y"),
                              JOB_CODE=col_character(),
                              WAGE_SOURCE_1=col_factor(c("C", "S", "O")),
                              CERTIFIED_BEGIN_DATE=col_date("%m/%d/%Y"),
                              CERTIFIED_END_DATE=col_date("%m/%d/%Y"),
                              ## YR_SOURCE_PUB_1/2 have some weird
                              ## non-year values. I just cast them to
                              ## NA but they're probably from bad data
                              ## entry so the real values might be in
                              ## some other column in those rows.
                              YR_SOURCE_PUB_1=col_date("%Y"),
                              YR_SOURCE_PUB_2=col_date("%Y")

                              ))

## Remove rows which are all NA
df <- df %>% filter(rowSums(is.na(.)) != ncol(.))

## Recode WAGE_SOURCE_1 to match the codings for the other datasets
df$WAGE_SOURCE_1 <- df$WAGE_SOURCE_1 %>% recode_factor("C"="Collective Bargaining Agreement", "O"="Other", "S"="SESA")

## DOL_DECISION_DATE has an extra single digit at the end of many
## entries, so we have to sub out the space and number.
df$DOL_DECISION_DATE <- sub("( \\d)$", "", df$DOL_DECISION_DATE)
df$DOL_DECISION_DATE <- as.Date(df$DOL_DECISION_DATE, format="%m/%d/%Y")

dfl[[i-1]] <- df

df <- bind_rows(dfl)  ## Vertically concats the dataframes.

## df is now ~1M rows long w/ all of the data from 2002-2006
```

To write the data to a new file,

```{r}
write_csv(df, "../../data/clean/H1B_efile_FY02-FY06_clean.csv")
```

```{r}
rm(list=ls())
df <- read_csv("../../data/clean/H1B_efile_FY02-FY06_clean.csv")
```

The format for 2007-2017 is very different, and differs from year to year more than the data from 2002-2007, so these files will take some time to clean. The following code works for 2017, but breaks on 2016 and below.

```{r eval=FALSE}

i <- "17"
df <- read_csv(paste("../../data/raw/csv_copies/H1B_FY",i,".csv", sep=""),
               col_types=cols(EMPLOYER_PHONE=col_character(),
                              FULL_TIME_POSITION=col_factor(c("Y","N")),
                              "H-1B_DEPENDENT"=col_factor(c("Y","N")),
                              WAGE_UNIT_OF_PAY=col_factor(c("Year","Hour","Month","Bi-Weekly","Week")),
                              PW_UNIT_OF_PAY=col_factor(c("Year","Hour","Month","Bi-Weekly","Week")),
                              PW_SOURCE=col_factor(c("OES","Other","CBA","DBA","SCA")),
                              WILLFUL_VIOLATOR=col_factor(c("Y","N")),
                              CASE_SUBMITTED=col_date("%m/%d/%Y"),
                              DECISION_DATE=col_date("%m/%d/%Y"),
                              EMPLOYMENT_START_DATE=col_date("%m/%d/%Y"),
                              EMPLOYMENT_END_DATE=col_date("%m/%d/%Y"),
                              VISA_CLASS=col_factor(c("H-1B","E-3 Australian", "H-1B1 Singapore", "H-1B1 Chile"))
                              ))

df$NAICS_CODE <- as.factor(df$NAICS_CODE)
df$SOC_CODE <- as.factor(df$SOC_CODE)
summary(df)
```
